local ls = require("luascript")
local pdf = require("pdf")

local function buildPdf()
  pdf.create()
  pdf.text(20, 25, "PDF Preview Demo", 18)
  pdf.text(20, 35, "Generated by Lua in browser", 12)

  pdf.table(20, 50,
    {"No","Name","Score"},
    {
      {1,"Alice",90},
      {2,"Bob",85},
      {3,"Charlie",88}
    }
  )
end

ls.when("click", "#btnPreview", function()
  buildPdf()
  pdf.preview("#pdfPreview") -- tampilkan di iframe
end)

ls.when("click", "#btnDownload", function()
  buildPdf()
  pdf.save("demo.pdf") -- download
end)

ls.display("Ready. Click Preview / Download.")
